version: '3'

volumes:
  devfolio_local_postgres_data: {}
  devfolio_local_postgres_data_backups: {}
  devfolio_local_postgres_dev_db_data: {}
  devfolio_local_postgres_dev_db_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: devfolio_production_postgres
    container_name: devfolio_local_postgres
    volumes:
      - devfolio_local_postgres_data:/var/lib/postgresql/data:Z
      - devfolio_local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

  postgres_dev:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: devfolio_production_postgres
    container_name: devfolio_local_postgres_dev_db
    volumes:
      - devfolio_local_postgres_dev_db_data:/var/lib/postgresql/data:Z
      - devfolio_local_postgres_dev_db_data_backups:/backups:z
    ports:
      - "8432:5432"
    env_file:
      - ./.envs/.local/.postgres
  #   django:
  #     build:
  #       context: .
  #       dockerfile: ./compose/local/django/Dockerfile
  #     image: devfolio_local_django
  #     container_name: devfolio_local_django
  #     platform: linux/x86_64
  #     depends_on:
  #       - postgres
  #     volumes:
  #       - .:/app:z
  #     env_file:
  #       - ./.envs/.local/.django
  #       - ./.envs/.local/.postgres
  #     ports:
  #       - "8000:8000"
  #     command: /start


  # docs:
  #   image: devfolio_local_docs
  #   container_name: devfolio_local_docs
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./devfolio:/app/devfolio:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs
