# Generated by Django 3.2.12 on 2022-04-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepagecarouselimages_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='site_description',
            field=models.CharField(blank=True, default='Company Name', max_length=100, null=True),
        ),
    ]
