# Generated by Django 3.2.12 on 2022-04-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_landingpage_site_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='site_description',
            new_name='company_name',
        ),
    ]
