# Generated by Django 3.2.12 on 2022-04-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_landingpage_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='company_name',
        ),
    ]
