# Generated by Django 3.2.12 on 2022-04-08 11:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220408_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='download_buttons',
            field=wagtail.core.fields.StreamField([('buttons', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Button text', max_length=50)), ('disabled', wagtail.core.blocks.BooleanBlock(default=False, help_text='Show button as disabled', required=False)), ('icon', wagtail.core.blocks.CharBlock(default='ai-arrow-down-circle mt-n1 me-2', help_text='Set a CSS class for the button icon', max_length=50)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
