# Generated by Django 3.2.12 on 2022-04-08 12:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_landingpage_download_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('portfolio_carousel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, null=True))])), ('usps', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='What I Do Best', help_text='Add your Unique Selling Points')), ('usps', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Choose a title')), ('description', wagtail.core.blocks.TextBlock(help_text='Describe a Unique Selling Point', rows=2)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Select image'))])))])), ('skill_cards', wagtail.core.blocks.StructBlock([('skill_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('skill', wagtail.core.blocks.CharBlock(help_text='A personal skill to showcase on the page', max_length=100)), ('categories', wagtail.snippets.blocks.SnippetChooserBlock('blog.SkillCategory', required=False))])))])), ('testimonials', wagtail.core.blocks.StructBlock([('testimonials', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(help_text='Quote text')), ('author', wagtail.core.blocks.CharBlock(help_text='Author of quote'))])))])), ('testimonial', wagtail.snippets.blocks.SnippetChooserBlock(target_model='testimonials.Testimonial', template='streams/testimonial.html'))], blank=True, null=True),
        ),
    ]
