# Generated by Django 4.1.4 on 2022-12-14 07:26

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_landingpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "portfolio_carousel",
                        wagtail.blocks.StructBlock(
                            [("title", wagtail.blocks.CharBlock(blank=True, null=True))]
                        ),
                    ),
                    (
                        "usps",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        default="What I Do Best",
                                        help_text="Add your Unique Selling Points",
                                    ),
                                ),
                                (
                                    "usps",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Choose a title"
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Describe a Unique Selling Point",
                                                        rows=2,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Select image"
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "skill_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "skill_cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "skill",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="A personal skill to showcase on the page",
                                                        max_length=100,
                                                    ),
                                                ),
                                                (
                                                    "categories",
                                                    wagtail.snippets.blocks.SnippetChooserBlock(
                                                        "blog.SkillCategory",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "testimonials",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "testimonials",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "text",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Quote text"
                                                    ),
                                                ),
                                                (
                                                    "author",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Author of quote"
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "testimonial",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            target_model="testimonials.Testimonial",
                            template="streams/testimonial.html",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="buttons",
            field=wagtail.fields.StreamField(
                [
                    (
                        "buttons",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Button text", max_length=50
                                    ),
                                ),
                                (
                                    "disabled",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="Show button as disabled",
                                        required=False,
                                    ),
                                ),
                                (
                                    "section_id",
                                    wagtail.blocks.CharBlock(
                                        help_text="Jump to section, i.e. 'about' jumps to #about on the same page",
                                        max_length=50,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="download_buttons",
            field=wagtail.fields.StreamField(
                [
                    (
                        "buttons",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Button text", max_length=50
                                    ),
                                ),
                                (
                                    "disabled",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        help_text="Show button as disabled",
                                        required=False,
                                    ),
                                ),
                                (
                                    "icon",
                                    wagtail.blocks.CharBlock(
                                        default="ai-arrow-down-circle mt-n1 me-2",
                                        help_text="Set a CSS class for the button icon",
                                        max_length=50,
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
