# Generated by Django 3.2.12 on 2022-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetailpage',
            name='live_url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfoliodetailpage',
            name='live_url_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliodetailpage',
            name='repo_url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
