# Generated by Django 3.2.12 on 2022-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220409_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetailpage',
            name='live_url_popup_text',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
