# Generated by Django 4.1.4 on 2022-12-14 07:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfoliodetailpage_live_url_popup_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliodetailpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "images",
                        wagtail.images.blocks.ImageChooserBlock(
                            template="streams/carousel.html"
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfoliodetailpage",
            name="text",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        blank=True, null=True, required=False
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        blank=True, null=True, required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
