# Generated by Django 3.2.12 on 2022-04-08 12:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_companydetailssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetailssettings',
            old_name='name',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='companydetailssettings',
            old_name='description',
            new_name='status',
        ),
        migrations.AddField(
            model_name='companydetailssettings',
            name='info_fields',
            field=wagtail.core.fields.StreamField([('info_fields', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('text', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False))]))], blank=True, null=True),
        ),
    ]
