# Generated by Django 3.2.12 on 2022-04-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20220408_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetailssettings',
            name='info_fields',
        ),
    ]
