# Generated by Django 3.2.12 on 2022-04-08 12:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_remove_companydetailssettings_info_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailssettings',
            name='info_fields',
            field=wagtail.core.fields.StreamField([('info_fields', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('text', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False))]))], blank=True, null=True),
        ),
    ]
