# Generated by Django 3.2.12 on 2022-04-08 12:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_companydetailssettings_info_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetailssettings',
            name='info_fields',
        ),
        migrations.AddField(
            model_name='companydetailssettings',
            name='details',
            field=wagtail.core.fields.StreamField([('details', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
