# Generated by Django 3.2.12 on 2022-04-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_companydetailssettings_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetailssettings',
            name='details',
        ),
    ]
