# Generated by Django 3.2.12 on 2022-04-08 13:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_remove_companydetailssettings_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailssettings',
            name='details',
            field=wagtail.core.fields.StreamField([('details', wagtail.core.blocks.RichTextBlock(form_classname='fs-sm text-light opacity-60', template='streams/rich_text_block.html'))], blank=True, null=True),
        ),
    ]
