# Generated by Django 3.2.12 on 2022-04-08 13:37

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_companydetailssettings_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailssettings',
            name='enable_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companydetailssettings',
            name='details',
            field=wagtail.core.fields.StreamField([('details', wagtail.core.blocks.RichTextBlock(template='streams/rich_text_block.html'))], blank=True, null=True),
        ),
    ]
