# Generated by Django 3.2.12 on 2022-04-08 13:43

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_auto_20220408_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetailssettings',
            old_name='enable_details',
            new_name='enable_address',
        ),
        migrations.RemoveField(
            model_name='companydetailssettings',
            name='details',
        ),
        migrations.AddField(
            model_name='companydetailssettings',
            name='address',
            field=wagtail.core.fields.StreamField([('address', wagtail.core.blocks.RichTextBlock(template='streams/rich_text_block.html'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetailssettings',
            name='company_ids',
            field=wagtail.core.fields.StreamField([('company_ids', wagtail.core.blocks.RichTextBlock(template='streams/rich_text_block.html'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetailssettings',
            name='enable_company_ids',
            field=models.BooleanField(default=True),
        ),
    ]
